var constraints = [
    "do not use the tonic chord nor the root note",
    "<b>reverse samples</b></br>your main motif is a reversed sample",
    "use at most 2 different chords",
    "do not use major or minor scale",
    "write a score for your favorite movie/tv show",
    "write while standing",
    "use samples from a song you last listened to",
    "<b>slow down</b></br>max bpm 70",
    "at most 2 instruments playing simultaneously",
    "use a tempo change during the song",
    "change a style unexpectedly during the song",
    "your melody can only use 3 different notes</br>(octaves dont count as a different note)",
    "arpeggiate, arpeggiate, arpeggiate...",
    "remix an old project of yours",
    "if your yesterday was a movie - write a soundtrack for it",
    "use a sound you hate or sample from a song you hate",
    "work with silence",
    "no drums allowed",
    "use an instrument you dont play</br>(sax, harp, cello,...)",
    "5/4", "7/8", "3/4", "9/8",
    "<b>cabbage</b></br>notes of your melody",
    "<b>sine wave</b></br>use it to drive the volume/tempo/atmosphere",
    "\"the lick\"",
    "repetition legitimizes,</br>repetition legitimizes,</br>repetition legitimizes,</br>repetition legitimizes,</br>repetition legitimizes,</br>...",
    "pick 2 other constraints and combine them", "pick 3 other constraints and combine them",
    "score a horror movie",
    "score a love story",
    "go to <u><a href=\"https://plugins4free.com/\">vst4free</a></u> and use the weirdest looking device",
    "no loops allowed",
    "no reverb allowed",
    "use an instance of 60s reverb",
    "<b>reverse structure</b></br>the laudest part of the song must be the beginning",
    "think for 5 minutes before you start creating",
    "glitch",
    "use the first preset you hear",
    "select instruments just by the name, not by the sound",
    "use symmetry",
    "<b>use math</b></br>addition, substraction, multiplication,...",
    "<a href=\"https://randomwordgenerator.com\">pick a random word</a> and try to express it with music",
    "add an easter egg",
    "make a melody from the last sentence you heard",
    "use prime numbers",
    "use only one drum sound",
    "use only one synth sound",
    "use only one sample",
    "use vocals",
    "rainy sunday morning",
    "first date",
    "only use sounds you recorded",
    "\"borrow\" someone's melody",
    "make an alternative version while making the original one",
    "write a cliffhanger",
    "the entire piece is a build-up",
    "score your last night's dream",
    "make green music",
    "make blue music",
    "make red music"
];

function foo(){
    let newCon = constraints[Math.floor(Math.random()*constraints.length)];
    document.getElementById("constraint-text").innerHTML = newCon;
}